#!perl

# AUTHORITY
# DATE
# DIST
# VERSION

use 5.010001;
use strict;
use warnings;
use Perinci::CmdLine::Classic;

my $cmd = Perinci::CmdLine::Classic->new(
    url => '/File/Trash/EmptyFiles/Undoable/',
    subcommands => {
        trash         => {
            url  => '/File/Trash/EmptyFiles/Undoable/trash_all_empty_files',
        },
        list_contents => {
            url  => '/File/Trash/Undoable/list_trash_contents',
            undo => 0,
        },
        empty         => {
            url  => '/File/Trash/Undoable/empty_trash',
            pass_cmdline_object => 1,
            undo => 0,
        },
    },
    default_subcommand => 'trash',
    undo => 1,
    log => 1,
    log_level => 'info',
);

# share undo dir with trash-u
require File::HomeDir;
$cmd->undo_dir(File::HomeDir->my_home . "/.trash-u");

delete $cmd->common_opts->{list};

$cmd->common_opts->{empty} = {
    getopt  => 'empty',
    handler => sub {
        my ($go, $val, $r) = @_;
        $r->{subcommand_name} = 'empty';
        $r->{subcommand_name_from} = '--cmd'; # XXX not exactly accurate
        $r->{skip_parse_subcommand_argv} = 1;
    },
};

$cmd->common_opts->{list_contents} = {
    getopt  => 'list-contents',
    handler => sub {
        my ($go, $val, $r) = @_;
        $r->{subcommand_name} = 'list_contents';
        $r->{subcommand_name_from} = '--cmd'; # XXX not exactly accurate
        $r->{skip_parse_subcommand_argv} = 1;
    },
};

$cmd->run;

1;
# ABSTRACT:
# PODNAME:

=head1 SYNOPSIS

 # trash all empty files in the current directory tree, but in simulation mode,
 # not really trashing the files
 % VERBOSE=1 trash-all-empty-files-u --dry-run

 # trash all empty files for real
 % trash-all-empty-files-u

 # list trash contents
 % trash-all-empty-files-u --list-contents
 % trash-u --list-contents

 # oops, made a mistake; no worry, let's undo; now previous trashing is reversed
 % trash-all-empty-files --undo
 % trash-u --undo


=head1 DESCRIPTION

This command-line program is an interface to
L<File::Trash::EmptyFiles::Undoable>, which in turn uses
L<File::Trash::Undoable>, which in turn uses L<File::Trash::FreeDesktop>.

It is basically a combination for L<delete-all-empty-files> + L<trash-u>.

This program has not yet been tested extensively. Use with caution.


=head1 SEE ALSO

L<File::Trash::Undoable> and L<trash-u>

L<App::FileRemoveUtils> and L<delete-all-empty-files>
